<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Charts extends MY_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('charts_model');
        is_user_loggedin();
    }

    public function get_charts()
    {
        $currentDate = date('Y-m-d');
        $params['startdate'] = date('Y-m-d', strtotime('-7 days', strtotime($currentDate)));
        $params['enddate'] = $currentDate;

        $bar_chart = $this->charts_model->get_bar_chartsBydate($params);
        $data['bar_chart'] = json_encode($bar_chart);

        $pie_chart = $this->charts_model->get_piecharts();
        $data['pie_chart'] = json_encode($pie_chart);

        $data['_view'] = 'dashboard_charts/main';
        $this->load->view('layouts/main', $data);
    }
    public function get_chartsByValue()
    {
        $params = $this->input->post('pie_chart');
        $pie_chart = $this->charts_model->get_pie_chartsByValue($params);
        echo json_encode($pie_chart);
    }
    public function bar_chartBydate()
    {
        $params['startdate'] = $this->input->post('startdate');
        $params['enddate'] = $this->input->post('enddate');
        $bar_chart = $this->charts_model->get_bar_chartsBydate($params);
        echo json_encode($bar_chart);
    }
}
