<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Transactions extends MY_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('transactions_model');
        is_user_loggedin();
    }

    public function index()
    {
        $total_records = $this->transactions_model->count_all_transactions();
        $data = $this->transactions_model->paginate_transactions($total_records);
        // print_r($data['transactions']);
        $data['total_records'] = $total_records;
        $data['_view'] = 'transaction/index';
        $this->load->view('layouts/main', $data);
    }

    public function add_transaction()
    {
        if (isset($_POST) && count($_POST) > 0) {
            $this->load->library('form_validation');
            $this->form_validation->set_rules('order_id', 'Order ID', 'is_unique[transactions.order_id]',[
                       'is_unique' => 'This order was already transactioned.'
                    ]);
            $this->form_validation->set_rules('purchase_id', 'Purchase ID', 'required');
            $this->form_validation->set_rules('total_cost', 'Amount', 'required');
            $this->form_validation->set_rules('pay_out', 'Pay Out', 'required');
            $this->form_validation->set_rules('transaction_date', 'Dransaction Date', 'required');

            if ($this->form_validation->run()) {
                $user_email = $this->input->post('user');
                $id  = $this->transactions_model->get_user_id($user_email);
                if (is_array($id) && !empty($id) && count($id) > 0) {
                    $data['order_id'] = $this->input->post('order_id');
                    $data['purchase_id'] = $this->input->post('purchase_id');
                    $data['amount'] = $this->input->post('total_cost');
                    $data['pay_out'] = $this->input->post('pay_out');
                    $data['created_date'] = date('Y-m-d h:i:sa');
                    $data['transaction_date'] = $this->input->post('transaction_date');
                    $data['created_by'] = $_SESSION['user_id'];
                    $data['user'] = $id[0]['id'];
                    $this->transactions_model->add_transaction($data);
                    echo json_encode(array('status' => 'success', 'message' => 'Transaction added successfully'));
                    flash_message('success', 'Transaction added successfully');
                    exit;
                    // $data['success_response'] = 'transaction added successfully';
                } else {
                    echo json_encode(array('status' => 'error', 'message' => 'User email not found'));
                    exit;
                    // $data['error_response'] = 'User email not found';
                }
            } else {
                echo json_encode(['status' => 'error', 'message' => strip_tags(validation_errors())]);
                exit;
                // $data['error_response'] = validation_errors();
            }
        }
        $data['_view'] = 'transaction/add';
        $this->load->view('layouts/main', $data);
    }

    public function download_transaction()
    {
        $data['_view'] = 'transaction/download_transaction';
        $this->load->view('layouts/main', $data);
    }

    public function download_transaction_file()
    {
        $data = array();
        $card_type = $this->input->post('cardType');
        $order_id = $this->input->post('orderID');
        $lastUserIDs = $this->input->post('last_user_ids') ?? [];

        $order_exists = $this->transactions_model->get_order_exists($order_id);
        
        if ($order_exists) {
            echo json_encode(array(
                'status' => 'error',
                'message' => 'This order was already bought.'
            ));
            exit;
        }
        

        // Validate if order_id already exists in transactions
        if (!empty($order_id)) {
            $existing_transaction = $this->transactions_model->check_order_exists($order_id, $card_type);
            if ($existing_transaction) {
                // Check if user confirmed to proceed
                $force_proceed = $this->input->post('force_proceed', true);

                if ($force_proceed !== 'yes') {
                    // Return warning message
                    echo json_encode(array(
                        'status' => 'warning',
                        'message' => 'This order was already bought, are you sure you want to proceed?',
                        'order_id' => $order_id
                    ));
                    exit;
                }
            }
        }

        $data = $this->transactions_model->get_file_download_data($card_type, $lastUserIDs);
        if (is_array($data) && !empty($data)) {
            echo json_encode($data);
        } else {
            echo 'false';
        }
        exit;
    }


    // function download($data)
    // {
    //     $file_name = site_url('resources/files/user.txt');

    //     // Load the download helper
    //     $this->load->helper('download');

    //     // Force download the file
    //     force_download($file_name, $data);
    // }

    public function update_transaction($tid)
    {
        $result = $this->transactions_model->get_transaction_by_id($tid);

        if (is_array($result) && !empty($result) && count($result) > 0) {
            if (isset($_POST) && is_array($_POST) && !empty($_POST)) {
                $user_email = $this->input->post('user');
                $id  = $this->transactions_model->get_user_id($user_email);

                if (is_array($id) && !empty($id)) {
                    $data['order_id'] = $this->input->post('order_id');
                    $data['purchase_id'] = $this->input->post('purchase_id');
                    $data['amount'] = $this->input->post('total_cost');
                    $data['pay_out'] = $this->input->post('pay_out');
                    $data['transaction_date'] = $this->input->post('transaction_date');
                    $data['created_by'] = $_SESSION['user_id'];
                    $data['user'] = $id[0]['id'];
                    $update_result = $this->transactions_model->update_transaction($tid, $data);

                    if ($update_result == true) {
                        $data['success_response'] = 'transaction Updated successfully';
                    } else {
                        $data['error_response'] = 'Failed to Update Transaction';
                    }
                } else {
                    $data['error_response'] = 'User email not found';
                }
            }

            $data['tid'] = $tid;
            $data['transaction_data'] = $result;
            $data['_view'] = 'transaction/update';
            $this->load->view('layouts/main', $data);
        } else {
            redirect('');
            return false;
        }
    }

    public function delete_transaction($id)
    {
        $this->transactions_model->delete_transaction($id);
        redirect('');
        return true;
    }
}
