<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class User extends MY_Controller
{
    function __construct()
    {
        parent::__construct();
        $this->load->model('user_model');
        is_user_loggedin();
    }

    function add()
    {
        $data['modules'] = $this->config->item("modules");
        $this->load->library('form_validation');
        $this->form_validation->set_rules('first_name', 'First Name', 'required');
        $this->form_validation->set_rules('last_name', 'Last Name', 'required');
        $this->form_validation->set_rules('email', 'email', 'required');
        $this->form_validation->set_rules('email', 'email', 'is_unique[portal_users.email]');
        $this->form_validation->set_rules('password', 'Password', 'required');

        if ($this->form_validation->run()) {
            if (isset($_POST['add_user'])) {
                $params = array(
                    'first_name' => $this->input->post('first_name'),
                    'last_name' => $this->input->post('last_name'),
                    'email' => $this->input->post('email'),
                    'password' => $this->input->post('password'),
                    'modules' => json_encode($this->input->post('modulesid')),
                    'created_by' => $_SESSION['user_id'],
                    'created_date' => date("m-d-Y"),
                    'status' => 'Y',
                );
            }
            $this->user_model->add_user($params);
            $data['success_response'] = 'user added successfully';
        }

        $data['_view'] = 'users/add_user';
        $this->load->view('layouts/main', $data);
    }

    function edit($id)
    {
        $data['modules'] = $this->config->item("modules");
        $data['user_id'] = $id;
        $data['user'] = $this->user_model->get_user($id);
        $data['acl_module'] = json_decode($data['user'][0]['modules'], true);
        $this->load->library('form_validation');
        $email = $this->input->post('email');

        $this->form_validation->set_rules('email', 'email', 'required');
        if ($data['user'][0]['email'] !=  $email) {
            $this->form_validation->set_rules('email', 'email', 'is_unique[portal_users.email]');
        }
        $this->form_validation->set_rules('first_name', 'First Name', 'required');

        if ($this->form_validation->run()) {
            if (isset($_POST['add_user'])) {
                $params = array(
                    'id' => $id,
                    'first_name' => $this->input->post('first_name'),
                    'last_name' => $this->input->post('last_name'),
                    'email' => $email,
                    'modules' => json_encode($this->input->post('modulesid')),
                    'created_by' => $_SESSION['user_id'],
                    'updated_date' => date("m-d-Y"),
                    'status' => 'Y',
                    'password' => $data['user'][0]['password']
                );
            }
            if (isset($_POST['password']) && !empty($_POST['password'])) {
                $this->form_validation->set_rules('password', 'password', 'required');
                $this->form_validation->set_rules('confirm_password', 'passwordConfirmation', 'required|matches[password]');
                $params['password'] = $this->input->post('password');
                $params['confirm_password'] = $this->input->post('confirm_password');
            }

            $this->user_model->update_user($params);
            $data['success_response'] = 'user updated successfully';
        }

        $data['_view'] = 'users/edit_user';
        $this->load->view('layouts/main', $data);
    }

    function list()
    {
        $data['users'] = $this->user_model->get_all_user();
        $data['_view'] = 'users/index';
        $this->load->view('layouts/main', $data);
    }

    function delete($id)
    {
        $this->user_model->delete_user($id);
        redirect('list');
    }

    function add_normal_user()
    {
        if (isset($_POST) && !empty($_POST)) {
            $this->load->library('form_validation');
            // $this->form_validation->set_rules('email', 'email', 'required|callback_check_user');
            $this->form_validation->set_rules('email', 'email', 'is_unique[users.email]');
            $this->form_validation->set_rules('password', 'Password', 'required');
            $this->form_validation->set_rules('cvv', 'CVV', 'required');
            $this->form_validation->set_rules('card_type', 'card_type', 'required');

            if ($this->form_validation->run()) {
                $redirect_to = $this->input->post('redirect_to');
                $params = array(
                    'email' => $this->input->post('email'),
                    'password' => $this->input->post('password'),
                    'cvv' => $this->input->post('cvv'),
                    'card_type' => $this->input->post('card_type'),
                    'created_by' => $_SESSION['user_id'],
                    'created_datetime' => date("Y-m-d h:i:sa"),
                    'status' => 'Y',
                );
                $result = $this->user_model->add_normal_user($params);

                if ($result == true) {
                    $data['success_response'] = 'User added successfully';
                    flash_message('success', 'User added successfully');
                    if (!empty($redirect_to) && $redirect_to == 'LIMIT') {
                        redirect(site_url('add_transaction'));
                    }
                    redirect(site_url('normal_user'));
                } else {
                    $data['error_response'] = 'Failed to add User';
                    flash_message('error', 'Failed to add User');
                }
            }
        }

        $data['_view'] = 'normal_user/add_normal_user';
        $this->load->view('layouts/main', $data);
    }

    function check_user()
    {
        $email = $this->input->post('email'); // get first name
        $card_type = $this->input->post('card_type'); // get last name
        // $this->db->select('user_id');
        $this->db->from('users');
        $this->db->where('email', $email);
        $this->db->where('card_type', $card_type);
        $query = $this->db->get();
        $num = $query->num_rows();
        if ($num > 0) {
            $this->form_validation->set_message('check_user', 'email already exist with same card type'); // set your message
            return FALSE;
        } else {
            return TRUE;
        }
    }

    public function delete_normal_user($id)
    {
        $this->user_model->delete_normal_user($id);
        redirect('normal_user');
        return true;
    }

    public function edit_normal_user($id)
    {
        $data['user'] = $this->user_model->get_user_by_id($id);
        if (isset($_POST) && !empty($_POST)) {
            $this->load->library('form_validation');
            $this->form_validation->set_rules('email', 'email', 'required');
            $email = $this->input->post('email');

            if ($data['user'][0]['email'] !=  $email) {
                $this->form_validation->set_rules('email', 'email', 'is_unique[users.email]');
            }

            $this->form_validation->set_rules('password', 'Password', 'required');

            if ($this->form_validation->run()) {
                $params = array(
                    'email' => $email,
                    'password' => $this->input->post('password'),
                    'card_type' => $this->input->post('card_type'),
                    'cvv' => $this->input->post('cvv'),
                    'updated_by' => $_SESSION['user_id'],
                    'updated_datetime' => date("Y-m-d h:i:sa"),
                    'status' => 'Y',
                    'id' => $id,
                );
                $result = $this->user_model->edit_normal_user($params);

                if ($result == true) {
                    $data['success_response'] = 'User update successfully';
                } else {
                    $data['error_response'] = 'Failed to update User';
                }
                $data['user'] = $this->user_model->get_user_by_id($id);
            }
        }

        $data['id'] = $id;
        if (is_array($data['user']) && !empty($data['user'])) {
            $data['_view'] = 'normal_user/edit_normal_user';
            $this->load->view('layouts/main', $data);
        } else {
            redirect('normal_user');
        }
    }

    public function normal_user_ajax()
    {

        if (!$this->input->is_ajax_request()) {
            show_404();
        }

        $result = $this->user_model->all_normal_users();
        $total_records = $this->user_model->count_all_normal_users();

        echo json_encode([
            'draw' => (int) $this->input->post('draw'),
            'recordsTotal' => $total_records,
            'recordsFiltered' => $result['filtered'],
            'data' => $result['data']
        ]);
        exit;
    }
}
