<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Transactions_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    public function get_all_transactions()
    {
        $sql = 'Select t.id, t.order_id, t.purchase_id, t.amount, t.pay_out, u.email, t.transaction_date from transactions t LEFT JOIN users u on u.id = t.user';
        $result = $this->db->query($sql);
        if ($result->num_rows() > 0) {
            return $result->result_array();
        } else {
            return array();
        }
    }

    public function paginated_transactions()
    {
        $search = $this->input->post('search')['value'] ?? '';
        $start  = (int) $this->input->post('start');
        $length = (int) $this->input->post('length');

        $this->db->select('t.id, t.order_id, t.purchase_id, t.amount, t.pay_out, u.email, t.transaction_date');
        $this->db->from('transactions t');
        $this->db->join('users u', 'u.id = t.user', 'left');

        if (!empty($search)) {
            $this->db->group_start();
            $this->db->like('t.order_id', $search);
            $this->db->or_like('t.purchase_id', $search);
            $this->db->or_like('u.email', $search);
            $this->db->group_end();
        }

        $filtered_count = $this->db->count_all_results('', false);

        $this->db->order_by('t.id', 'DESC');
        $this->db->order_by($this->input->post('order')[0]['column'] ?? '0', $this->input->post('order')[0]['dir'] ?? 'desc');
        $this->db->limit($length, $start);

        $query = $this->db->get();

        return [
            'data' => $query->result_array(),
            'filtered' => $filtered_count
        ];
    }

    public function count_all_transactions()
    {
        return $this->db->count_all('transactions');
    }


    public function get_user_id($email)
    {
        $query = "SELECT id FROM users WHERE email = '" . $email . "'";
        $result = $this->db->query($query);
        if ($result->num_rows() > 0) {
            return $result->result_array();
        } else {
            return array();
        }
    }

    public function add_transaction($data)
    {
        return  $this->db->insert('transactions', $data);
    }

    public function get_file_download_data($card_type, $exclude_user_ids = [])
    {

        $date = (new DateTime("2025-12-25"))->format('Y-m-d H:i:s');
        if ($card_type != 'CD') {
            $query = " SELECT
                        u.id,u.email, u.password, u.cvv, u.card_type, u.created_datetime
                    FROM
                        users u
                    LEFT JOIN transactions t ON
                        t.user = u.id
                    WHERE
                        u.card_type = '" . $card_type . "' AND u.created_datetime > '" . $date . "'
                GROUP BY
                        u.id ";
        } else {
            // Skip Most Recent 1 Users
            $query = $this->cardTypeCDQuery($exclude_user_ids, $card_type, $date);
            // echo $query;exit;
        }

        $result = $this->db->query($query);
        if ($result->num_rows() > 0) {
            return $result->result_array();
        } else {
            return array();
        }
    }
    // Skip Most Recent 5 Users
    public function cardTypeCDQuery($exclude_user_ids, $card_type, $date)
    {
        $excludeQuery = "";
        if (!empty($exclude_user_ids)) {
            // $excludedList = implode(",", array_filter($exclude_user_ids, 'strlen'));
            $excludedList = end($exclude_user_ids);
            $excludeQuery .= " AND u.id NOT IN ($excludedList)";
        }
        $query = "WITH ranked_transactions AS (
                    SELECT
                        u.id,
                        u.email,
                        u.password,
                        u.cvv,
                        u.card_type,
                        u.created_datetime,
                        t.user,
                        t.created_date,
                        ROW_NUMBER() OVER (
                            PARTITION BY u.id
                            ORDER BY t.created_date DESC
                        ) AS rn
                    FROM users u
                    LEFT JOIN transactions t ON t.user = u.id
                    WHERE u.created_datetime > '2025-12-25'
                    AND u.card_type = 'CD'
                    ORDER BY RAND()
                    LIMIT 5
                ),
                latest_user AS (
                    SELECT rt.user
                    FROM ranked_transactions rt
                    WHERE rt.user IS NOT NULL
                    AND rt.rn = 1 
                    ORDER BY rt.created_date DESC
                    LIMIT 1
                )
                SELECT *
                FROM ranked_transactions rt
                WHERE rt.rn = 1
                AND (
                        (SELECT COUNT(DISTINCT id) FROM ranked_transactions) = 1
                        OR NOT EXISTS (
                            SELECT 1
                            FROM latest_user lu
                            WHERE lu.user = rt.id
                        )
                )
                ORDER BY RAND()
                LIMIT 1;";
        return $query;
    }
    public function check_order_exists($order_id, $card_type)
    {
        $this->db->select('u.card_type, t.order_id');
        $this->db->from('transactions t');
        $this->db->join('users u', 't.user = u.id', 'left');
        $this->db->where('t.order_id', $order_id);

        if (!empty($card_type)) {
            $this->db->where('u.card_type', strtoupper($card_type));
        }
        $query = $this->db->get();

        if ($query->num_rows() > 0) {
            return $query->row();
        }

        return false;
    }

    public function delete_transaction($id)
    {
        $query = "DELETE FROM `transactions` WHERE id = $id";
        return $this->db->query($query);
    }

    public function get_transaction_by_id($id)
    {
        $sql = 'Select t.id, t.order_id, t.purchase_id, t.amount, t.pay_out,u.email, t.transaction_date from transactions t LEFT JOIN users u on u.id = t.user where t.id = ' . $id;
        $result = $this->db->query($sql);
        if ($result->num_rows() > 0) {
            return $result->result_array();
        } else {
            return array();
        }
    }

    public function update_transaction($id, $params)
    {
        $query = "UPDATE `transactions` SET `order_id`='" . $params['order_id'] . "',`purchase_id`='" . $params['purchase_id'] . "',`transaction_date`='" . $params['transaction_date'] . "',`user`='" . $params['user'] . "',`amount`='" . $params['amount'] . "',`pay_out`='" . $params['pay_out'] . "',`created_by`='" . $params['created_by'] . "' WHERE id = {$id}";
        return $this->db->query($query);
    }

    function get_order_exists($order_id)
    {
        $this->db->select('*');
        $this->db->from('transactions');
        $this->db->where('order_id', $order_id);
        $query = $this->db->get();

        if ($query->num_rows() > 0) {
            return $query->row();
        } else {
            return false;
        }
    }
}
