<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class Transactions_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    public function get_all_transactions()
    {
        $sql = 'Select t.id, t.order_id, t.purchase_id, t.amount, t.pay_out, u.email, t.transaction_date from transactions t LEFT JOIN users u on u.id = t.user';
        $result = $this->db->query($sql);
        if ($result->num_rows() > 0) {
            return $result->result_array();
        } else {
            return array();
        }
    }

    public function paginated_transactions($limit, $offset)
    {
        $this->db->select('t.id, t.order_id, t.purchase_id, t.amount, t.pay_out, u.email, t.transaction_date');
        $this->db->from('transactions t');
        $this->db->join('users u', 'u.id = t.user', 'left');
        $this->db->order_by('t.id', 'DESC');
        $this->db->limit($limit, $offset);

        $query = $this->db->get();
        return $query->result_array();
    }

    public function count_all_transactions()
    {
        return $this->db->count_all('transactions');
    }


    public function get_user_id($email)
    {
        $query = "SELECT id FROM users WHERE email = '" . $email . "'";
        $result = $this->db->query($query);
        if ($result->num_rows() > 0) {
            return $result->result_array();
        } else {
            return array();
        }
    }

    public function add_transaction($data)
    {
        return  $this->db->insert('transactions', $data);
    }

    public function get_file_download_data($card_type, $exclude_user_ids = [])
    {

        $counter = strtoupper($card_type) == 'LIMIT' ? 1 : 3;
        $date = (new DateTime("2024-01-28"))->format('Y-m-d H:i:s');
        if ($card_type != 'CD') {
            $query = " SELECT
                        u.id,u.email, u.password, u.cvv, u.card_type, u.created_datetime
                    FROM
                        users u
                    LEFT JOIN transactions t ON
                        t.user = u.id
                    WHERE
                        u.card_type = '" . $card_type . "' AND u.created_datetime > '" . $date . "'
                GROUP BY
                        u.id
                    HAVING
                        COUNT(t.user) < '" . $counter . "'  order by rand() limit 1";
        } else {
            // Skip Most Recent 1 Users
            $query = $this->cardTypeCDQuery($exclude_user_ids, $card_type, $date);
            // echo $query;exit;
        }

        $result = $this->db->query($query);
        if ($result->num_rows() > 0) {
            return $result->result_array();
        } else {
            return array();
        }
    }
    // Skip Most Recent 5 Users
    public function cardTypeCDQuery($exclude_user_ids, $card_type, $date)
    {
        $excludeQuery = "";
        if (!empty($exclude_user_ids)) {
            // $excludedList = implode(",", array_filter($exclude_user_ids, 'strlen'));
            $excludedList = end($exclude_user_ids);
            $excludeQuery .= " AND u.id NOT IN ($excludedList)";
        }
        $query = "WITH user_transactions as (
            SELECT 
                u.id,
                u.email,
                u.password,
                u.cvv,
                u.card_type,
                u.created_datetime,
                t.user,
                t.created_date
            
            FROM users u 
            LEFT JOIN transactions t 
                ON t.user = u.id 
            WHERE  
                u.created_datetime > '" . $date . "' $excludeQuery
                AND u.card_type = '$card_type'
        ),

        latest_user as (
            SELECT DISTINCT
                user 
            FROM user_transactions 
            ORDER BY created_date DESC 
            LIMIT 1             
        )

        SELECT 
            ut.* 
        FROM 
            user_transactions ut
            
        WHERE 
            ut.id NOT IN (
                select user from latest_user
            )  

        ORDER BY 
            rand() LIMIT 1";
        return $query;
    }
    public function check_order_exists($order_id, $card_type)
    {
        $this->db->select('u.card_type, t.order_id');
        $this->db->from('transactions t');
        $this->db->join('users u', 't.user = u.id', 'left');
        $this->db->where('t.order_id', $order_id);

        if (!empty($card_type)) {
            $this->db->where('u.card_type', strtoupper($card_type));
        }
        $query = $this->db->get();

        if ($query->num_rows() > 0) {
            return $query->row();
        }

        return false;
    }

    public function delete_transaction($id)
    {
        $query = "DELETE FROM `transactions` WHERE id = $id";
        return $this->db->query($query);
    }

    public function get_transaction_by_id($id)
    {
        $sql = 'Select t.id, t.order_id, t.purchase_id, t.amount, t.pay_out,u.email, t.transaction_date from transactions t LEFT JOIN users u on u.id = t.user where t.id = ' . $id;
        $result = $this->db->query($sql);
        if ($result->num_rows() > 0) {
            return $result->result_array();
        } else {
            return array();
        }
    }

    public function update_transaction($id, $params)
    {
        $query = "UPDATE `transactions` SET `order_id`='" . $params['order_id'] . "',`purchase_id`='" . $params['purchase_id'] . "',`transaction_date`='" . $params['transaction_date'] . "',`user`='" . $params['user'] . "',`amount`='" . $params['amount'] . "',`pay_out`='" . $params['pay_out'] . "',`created_by`='" . $params['created_by'] . "' WHERE id = {$id}";
        return $this->db->query($query);
    }
    public function paginate_transactions($total_records)
    {
        $limit = 100;
        $page = max(1, (int) $this->input->get('page'));
        $offset = ($page - 1) * $limit;

        $data['transactions'] = $this->transactions_model->paginated_transactions($limit, $offset);
        $data['pagination'] = $this->build_pagination($page, $total_records, $limit);

        return $data;
    }

    public function build_pagination($page, $total_records, $limit)
    {
        $total_pages = (int) ceil($total_records / $limit);

        // No pagination needed
        if ($total_pages <= 1) {
            return '';
        }

        $max_links = 5;
        $half_links = floor($max_links / 2);

        // Calculate range
        $start = max(1, min($page - $half_links, $total_pages - $max_links + 1));
        $end = min($total_pages, $start + $max_links - 1);

        $base_url = site_url('');
        $links = ['<div class="pagination">'];

        // Previous link
        if ($page > 1) {
            $links[] = sprintf('<a href="%s?page=%d" rel="prev">&laquo;</a>', $base_url, $page - 1);
        }

        // First page + ellipsis
        if ($start > 1) {
            $links[] = sprintf('<a href="%s?page=1">1</a>', $base_url);
            if ($start > 2) {
                $links[] = '<span>...</span>';
            }
        }

        // Page numbers
        for ($i = $start; $i <= $end; $i++) {
            $links[] = ($i == $page)
                ? "<strong>$i</strong>"
                : sprintf('<a href="%s?page=%d">%d</a>', $base_url, $i, $i);
        }

        // Last page + ellipsis
        if ($end < $total_pages) {
            if ($end < $total_pages - 1) {
                $links[] = '<span>...</span>';
            }
            $links[] = sprintf('<a href="%s?page=%d">%d</a>', $base_url, $total_pages, $total_pages);
        }

        // Next link
        if ($page < $total_pages) {
            $links[] = sprintf('<a href="%s?page=%d" rel="next">&raquo;</a>', $base_url, $page + 1);
        }

        $links[] = '</div>';

        return implode('', $links);
    }

    function get_order_exists($order_id)
    {
        $this->db->select('*');
        $this->db->from('transactions');
        $this->db->where('order_id', $order_id);
        $query = $this->db->get();

        if ($query->num_rows() > 0) {
            return $query->row();
        } else {
            return false;
        }
    }
}
