<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */

class User_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }

    function add_user($params)
    {
        return  $this->db->insert('portal_users', $params);
    }

    function get_all_user()
    {
        $query = "SELECT * FROM `portal_users` ";
        $result = $this->db->query($query);

        if ($result->num_rows() > 0) {
            return $result->result_array();
        } else {
            return array();
        }
    }

    function get_user($user_id)
    {
        $query = "SELECT * FROM `portal_users` WHERE id = '$user_id' ;";
        $result = $this->db->query($query);

        if ($result->num_rows() > 0) {
            return $result->result_array();
        } else {
            return array();
        }
    }

    function delete_user($id)
    {
        $query = "DELETE FROM `portal_users` WHERE id = '$id' ;";
        return $this->db->query($query);
    }

    function update_user($params)
    {
        $query = " UPDATE
        `portal_users`
        SET
            first_name = '" . $params['first_name'] . "',
            last_name = '" . $params['last_name'] . "',
            password = '" . $params['password'] . "',
            modules = '" . $params['modules'] . "',
            updated_date = '" . $params['updated_date'] . "',
            created_by = '" . $params['created_by'] . "',
            email = '" . $params['email'] . "'
        WHERE
            id = '" . $params['id'] . "' ;";
        return $this->db->query($query);
    }

    public function add_normal_user($params)
    {
        return  $this->db->insert('users', $params);
    }

    public function all_normal_users()
    {
        $search = $this->input->post('search')['value'] ?? '';
        $start  = $this->input->post('start') ? (int) $this->input->post('start') : 0;
        $length = $this->input->post('length') ? (int) $this->input->post('length') : 10;

        $this->db->select('*');
        $this->db->from('users');

        if (!empty($search)) {
            $this->db->group_start();
            $this->db->like('email', $search);
            $this->db->like('id', $search);
            $this->db->group_end();
        }

        $filtered_count = $this->db->count_all_results('', false);
        $this->db->order_by('id', 'desc');
        $this->db->order_by($this->input->post('order')[0]['column'] ?? '0', $this->input->post('order')[0]['dir'] ?? 'desc');
        $this->db->limit($length, $start);

        $result = $this->db->get();
        return [
            'data' => $result->result_array(),
            'filtered' => $filtered_count
        ];
    }

    public function delete_normal_user($id)
    {
        $query = 'delete from users where id =' . $id;
        return $this->db->query($query);
    }

    function get_user_by_id($user_id)
    {
        $query = "SELECT * FROM `users` WHERE id = '$user_id' ;";
        $result = $this->db->query($query);

        if ($result->num_rows() > 0) {
            return $result->result_array();
        } else {
            return array();
        }
    }

    public function edit_normal_user($params)
    {
        // pr($params, 1);
        $query = "UPDATE
                `users`
            SET
                `password` = '" . $params['password'] . "',
                updated_datetime = '" . $params['updated_datetime'] . "',
                updated_by = '" . $params['updated_by'] . "',
                cvv = '" . $params['cvv'] . "',
                card_type = '" . $params['card_type'] . "',
                email = '" . $params['email'] . "'
            WHERE
                id = '" . $params['id'] . "' ;";
        return $this->db->query($query);
    }

    function count_all_normal_users() {

        return $this->db->count_all('users');
        
    }
}
